### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Yewx0310** [dotsnangles/causal-event-extractor#1]
I would like to know what the format of the dataset looks like

**Comment by dotsnangles** [comment]
the dataset I used was the usual bio tagged. I can't really share it though since it was provided from the company. cheers.

**Comment by dotsnangles** [comment]
you may want to build the lables of your dataset as following:

O-O-O-P_B-P_I-O-O-O

P means person in the context. search the web for BIO tagging schema. I am pretty sure you will find a way to build your own dataset soon.

I uploaded the project just to back up the model class. I don't think you want to use my preprocess routine in the repo since it is specifically for the dataset I used. good luck! 👍
